name:                uzelkey
version:             0.1.0.0
github:              "mem-memov/uzelkey"
license:             BSD3
author:              "Aleksandr Novikov"
maintainer:          "mem-memov@yandex.ru"
copyright:           "2021 Aleksandr Novikov"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mem-memov/uzelkey#readme>

dependencies:
- base >= 4.7 && < 5
- vector
- split
- mtl

library:
  source-dirs: src

executables:
  uzelkey-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - uzelkey

tests:
  uzelkey-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - uzelkey
    - hspec
